Feat: Add missing build artefact path handling to build process
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/python-project-build/action.yaml b/.github/actions/python-project-build/action.yaml
--- a/.github/actions/python-project-build/action.yaml
+++ b/.github/actions/python-project-build/action.yaml
@@ -12,9 +12,12 @@ inputs:
     default: "dist"
 
 outputs:
-  PUBLISH:
-    description: "Set true when a production build"
+  BUILD:
+    description: "Build [production|development]"
     value: ${{ steps.build.outputs.publish }}
+  DATETIME:
+    description: "Date and time stamp for build"
+    value: ${{ steps.setenv.outputs.datetime }}
 
 runs:
   using: "composite"
@@ -25,35 +28,51 @@ runs:
       run: |
         echo "Action triggered by: ${GITHUB_TRIGGERING_ACTOR}"
         echo "Using build artefact path: ${{ inputs.artefacts }}"
-        datetime=$(date +'%Y%m%d%H%M')
-        echo "Using date and time stamp: $datetime"
-        export datetime
+        if [ ! -d ${{ inputs.artefacts }} ]; then
+          echo -n "Creating directory for artefacts: ${{ inputs.artefacts }} "
+          if (mkdir -p ${{ inputs.artefacts }}); then
+            echo "SUCCESS"
+          else
+            echo "FAILED"
+            echo "Error: could not create output directory for build artefacts"
+            exit 1
+          fi
+        fi
+        datetime=$(date +'%Y-%m-%d-%H%M')
+        echo "Build date and time stamp: $datetime"
+        echo "datetime=$datetime" >> "$GITHUB_ENV"
         echo "datetime=${datetime}" >> "$GITHUB_OUTPUT"
 
-    - name: "Performing Build"
+    - name: "Perform package build"
       id: build
       shell: bash
       run: |
-        python -m pip install --upgrade pip
-        if [ -f tox.ini ]; then
-          pip install tox tox-gh-actions
-          echo "Found file: tox.ini"
-          echo "Building with command: tox -e build"
-          tox -e build
-        elif [ -f pyproject.toml ]; then
+        # Perform package build
+        python -m pip install -q --upgrade pip
+        if [ -f pyproject.toml ]; then
           echo "Found file: pyproject.toml"
           echo "Building with command: pdm build"
-          pdm build
+          pdm build --dest ${{ inputs.artefacts }}
+        elif [ -f tox.ini ]; then
+          echo "Found TOX configuration file: tox.ini"
+          echo "Attempting to install TOX..."
+          pip install -q --upgrade tox tox-gh-actions
+          echo "Attempting build with: tox -e build"
+          echo "WARNING: assumes build artefact path is valid"
+          tox -e build
         else
           echo "Neither file found: tox.ini/pyproject.toml"
-          pip install --upgrade build
           echo "Attempting build with: python -m build"
-          python -m build
+          pip -q --upgrade install build
+          python -m build --outdir ${{ inputs.artefacts }}
         fi
 
-        # Set flag to indicate production project build
-        if ! (ls ${{ inputs.artefacts }}/*.dev*.*); then
-          echo "publish=true" >> "$GITHUB_OUTPUT"
+        # Set build type based on artefact naming
+        if test -n "$(find ${{ inputs.artefacts }} -maxdepth 1 -name '**.dev*' -print -quit)"; then
+          echo "Artefact naming indicates development build"
+          echo "build=development" >> "$GITHUB_ENV"
+          echo "build=development" >> "$GITHUB_OUTPUT"
         else
-          echo "publish=false" >> "$GITHUB_OUTPUT"
+          echo "build=production" >> "$GITHUB_ENV"
+          echo "build=production" >> "$GITHUB_OUTPUT"
         fi
