Chore: test action update (#30)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/latest-semantic-tag/action.yaml b/.github/actions/latest-semantic-tag/action.yaml
--- a/.github/actions/latest-semantic-tag/action.yaml
+++ b/.github/actions/latest-semantic-tag/action.yaml
@@ -12,12 +12,39 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: "Report workflow environment"
+      id: vars
+      run: |
+        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
+        # Report GitHub workflow environment
+        echo "Github github.ref_name: ${{ github.ref_name }}"
+        echo "Github github.head_ref: ${{ github.head_ref }}"
+        echo "Github tag from GITHUB_REF: $RELEASE_VERSION"
+
+    - name: "Report/check output variables"
+      id: output
+      env:
+        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
+      run: |
+        echo "Release version: $RELEASE_VERSION"
+        echo ${{ steps.vars.outputs.tag }}
+
     - id: parse-tags
       name: "Determine latest semantic tag"
       shell: bash
       run: |
-        echo "Github github.ref_name: ${{ github.ref_name }}"
-        echo "Github github.head_ref: ${{ github.head_ref }}"
-        LATEST_TAG=$(git tag -l --sort=committerdate | grep -o 'v.*' | sort -r | head -1)
-        echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
-        echo "Tag = $LATEST_TAG"
+        set +vx
+        set -o pipefail
+        LATEST_TAG=$(git tag -l --sort=committerdate | grep -o 'v*.*.*' | sort -r | head -1)
+        if [ -z "$LATEST_TAG" ]; then
+          echo "Could not parse tags"
+          echo "Listing all tags:"
+          git tag -l
+          echo "Latest tag returned as:"
+          git tag -l --sort=committerdate | grep -o 'v*.*.*' | sort -r | head -1
+          exit 2
+        else
+          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
+          echo "Latest tag: $LATEST_TAG"
+        fi
