Feat: Implement synthetic tests for development tag action (#371)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -133,7 +133,7 @@ jobs:
           tag: "v1.2.3"
           type: "major"
 
-      - name: "Validate Incremented Tags"
+      - name: "Validate Incremented PROD Tags"
         shell: bash
         run: |
           # Check output from: semantic-tag-production
@@ -148,6 +148,53 @@ jobs:
           fi
           if [ "${{ steps.semantic-tag-production-major.outputs.tag }}" != "2.0.0" ]; then
             echo "Errors with: semantic-tag-production [major]"
+            ERRORS="true"
+          fi
+          if [ "$ERRORS" = "true" ]; then
+            echo "ERROR: check tag manipulation action/code"; exit 1
+          else
+            echo "All tag check tests passed, no errors found"
+          fi
+
+      - name: "Action: semantic-tag-development [patch]"
+        id: semantic-tag-development-patch
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/semantic-tag-development@main
+        with:
+          tag: "v2.9.6"
+          type: "patch"
+
+      - name: "Action: semantic-tag-development [minor]"
+        id: semantic-tag-development-minor
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/semantic-tag-development@main
+        with:
+          tag: "v1.8.3"
+          type: "minor"
+
+      - name: "Action: semantic-tag-development [major]"
+        id: semantic-tag-development-major
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/semantic-tag-development@main
+        with:
+          tag: "v4.1.1"
+          type: "major"
+
+      - name: "Validate Incremented DEV Tags"
+        shell: bash
+        run: |
+          # Check output from: semantic-tag-development
+          ERRORS="false"
+          if [ "${{ steps.semantic-tag-development-patch.outputs.tag }}" != "2.9.7-dev1" ]; then
+            echo "Errors with: semantic-tag-development [patch]"
+            ERRORS="true"
+          fi
+          if [ "${{ steps.semantic-tag-development-minor.outputs.tag }}" != "1.9.0-dev1" ]; then
+            echo "Errors with: semantic-tag-development [minor]"
+            ERRORS="true"
+          fi
+          if [ "${{ steps.semantic-tag-development-major.outputs.tag }}" != "5.0.0-dev1" ]; then
+            echo "Errors with: semantic-tag-development [major]"
             ERRORS="true"
           fi
           if [ "$ERRORS" = "true" ]; then
