Chore: Implement tests for new regex string extraction action (#400)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -49,6 +49,27 @@ jobs:
           fetch-tags: true
           # The semantic-tag-fetch action  currently contains a workaround for this behaviour
 
+      - name: "Action: string-extract-with-regex"
+        id: string-extract-with-regex
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/string-extract-with-regex@main
+        with:
+          filename: "pyproject.toml"
+          regex: '^name = ".*"$'
+          flags: "-E"
+
+      - name: "Validate: string-extract-with-regex"
+        shell: bash
+        run: |
+          # Check output from: string-extract-with-regex
+          PYTHON_PROJECT_NAME="${{ steps.string-extract-with-regex.outputs.extracted_string }}"
+          if [ "$PYTHON_PROJECT_NAME" != "osc-github-devops" ]; then
+            echo "ERROR: Python project name was not as expected"
+            echo "PYTHON_PROJECT_NAME: $PYTHON_PROJECT_NAME"; exit 1
+          else
+            echo "Returned project name correct: $PYTHON_PROJECT_NAME"
+          fi
+
       - name: "Action: python-project-name"
         id: python-project-name
         # yamllint disable-line rule:line-length
