Feat: Implement semantic tag validation tests (#217)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -54,6 +54,39 @@ jobs:
         with:
           path: "tests/dist"
 
+      - name: "Action: semantic-tag-validity [valid tag]"
+        id: semantic-tag-validate-good
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/semantic-tag-validity@main
+        with:
+          tag: v1.2.3
+
+      - name: "Action: semantic-tag-validity [junk tag]"
+        id: semantic-tag-validate-junk
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/semantic-tag-validity@main
+        with:
+          tag: v1.not-valid.3.garbage
+
+      - name: "Validate: semantic-tag-validity"
+        shell: bash
+        run: |
+          # Check output from: semantic-tag-validate-good/junk
+          ERRORS="false"
+          if [ "${{ steps.semantic-tag-validate-good.outputs.valid }}" != "true" ]; then
+            echo "Errors with: semantic-tag-validate v1.2.3"
+            ERRORS="true"
+          fi
+          if [ "${{ steps.semantic-tag-validate-junk.outputs.valid }}" != "false" ]; then
+            echo "Errors with: semantic-tag-increment v1.not-valid.3.garbage"
+            ERRORS="true"
+          fi
+          if [ "$ERRORS" = "true" ]; then
+            echo "ERROR: check semantic tag validation action/code"; exit 1
+          else
+            echo "All tag validation tests passed, no errors found"
+          fi
+
       - name: "Action: semantic-tag-latest"
         id: semantic-tag-latest
         # yamllint disable-line rule:line-length
