Chore: Update project name enumeeration actions (#395)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -49,29 +49,22 @@ jobs:
           fetch-tags: true
           # The semantic-tag-fetch action  currently contains a workaround for this behaviour
 
-      - name: "Action: python-project-naming"
-        id: python-project-naming
+      - name: "Action: python-project-name"
+        id: python-project-name
         # yamllint disable-line rule:line-length
-        uses: os-climate/osc-github-devops/.github/actions/python-project-naming@main
+        uses: os-climate/osc-github-devops/.github/actions/python-project-name@main
 
-      #- name: "Validate: python-project-naming"
-      #shell: bash
-      #run: |
-      # Check output from: python-project-naming
-      #ERRORS="false"
-      #if [ "${{ steps.semantic-tag-validate-good.outputs.valid }}" != "true" ]; then
-      #  ERRORS="true"
-      #fi
-      ##  echo "Errors with: semantic-tag-validate v1.2.3"
-      #if [ "${{ steps.semantic-tag-validate-junk.outputs.valid }}" != "false" ]; then
-      #  echo "Errors with: semantic-tag-production v1.not-valid.3.garbage"
-      #  ERRORS="true"
-      #fi
-      #if [ "$ERRORS" = "true" ]; then
-      #  echo "ERROR: check semantic tag validation action/code"; exit 1
-      #else
-      #  echo "All tag validation tests passed, no errors found"
-      #fi
+      - name: "Validate: python-project-name"
+        shell: bash
+        run: |
+          # Check output from: python-project-name
+          PYTHON_PROJECT_NAME="${{ steps.python-project-name.outputs.python_project_name }}"
+          if [ "$PYTHON_PROJECT_NAME" != "osc-github-devops" ]; then
+            echo "ERROR: Python project name was not as expected"
+            echo "PYTHON_PROJECT_NAME: $PYTHON_PROJECT_NAME"; exit 1
+          else
+            echo "Returned project name correct: $PYTHON_PROJECT_NAME"
+          fi
 
       - name: "Action: repository-classify-content"
         id: repository-classify-content
