Feat: Add further validation to 1Password testing (#265)
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/one-password-credentials.yaml b/.github/workflows/one-password-credentials.yaml
--- a/.github/workflows/one-password-credentials.yaml
+++ b/.github/workflows/one-password-credentials.yaml
@@ -17,7 +17,7 @@ jobs:
     name: "Access test credential"
     runs-on: "ubuntu-latest"
     steps:
-      - name: "Load secrets from OS-Climate Vault [Development/Testing]"
+      - name: "Load test note from OS-Climate Vault [Development/Testing]"
         uses: 1password/load-secrets-action@v2
         with:
           # Export loaded secrets as environment variables
@@ -28,9 +28,16 @@ jobs:
           TEST_NOTE_SHA: "op://67hdehutbpddhfbgm6ffjvdsbu/Test Secure Note/add more/sha1sum"
           OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_DEVELOPMENT }}
 
-      - name: "Print masked variables"
+      - name: "Print masked variables and validate"
         # Prints: Secret: ***
         run: |
           # Print masked variables
           echo "TEST_NOTE_LABEL: $TEST_NOTE_LABEL"
           echo "TEST_NOTE_SHA: $TEST_NOTE_SHA"
+          SHA1SUM=$(echo "$TEST_NOTE_LABEL" | sha1sum)
+          if [ "$SHA1SUM" == "$TEST_NOTE_SHA" ]; then
+            echo "Success: sha1sum of retrieved element matches expected value"
+          else
+            echo "Error: sha1sum of retrieved element did NOT match expected value"
+            exit 1
+          fi
